### ISSUE TITLE
Attempt to open an existing DAR causes error.

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#40] opened 2018-04-30 04:12 UTC
`ERROR:Cannot read property 'data' of undefined`

![open_bug](https://user-images.githubusercontent.com/2358535/39414932-4f97ec14-4c91-11e8-8cfe-4f816306bd10.gif)

**Comment by oliver----** [comment] 2018-04-30 04:54
@apawlik would it be possible that you zip'ped the specific folder and upload it here? You can drag'n'drop a zip-file into the textbox here (like with gifs)

**Comment by apawlik** [comment] 2018-04-30 05:07
@oliver---- Done! 
[dar-example.zip](https://github.com/stencila/desktop/files/1959599/dar-example.zip)

**Comment by oliver----** [comment] 2018-04-30 07:27
Thanks! I'll take a look.

**Comment by oliver----** [comment] 2018-04-30 07:49
Got down to the root of the error. Will fix it.

**Comment by oliver----** [comment] 2018-04-30 08:12
@apawlik Thanks for this. 50% of the problem is tracked now. I have added a PR with a quick-fix/workaround. 
The problem is: in the `manifest.xml` there is a reference to `sheet.xml` which is not there.
The missing 50% for us is to find out how this entry got there without storing the `sheet.xml` as well.

**Comment by oliver----** [comment] 2018-04-30 08:13
@michael pulling you in, so that you are aware of this potential problem

**Comment by nokome** [comment] 2018-05-08 05:15
This should be fixed by https://github.com/substance/texture/pull/511

**Closed by nokome** 2018-05-08 05:15 UTC
Labels: bug
